### ISSUE TITLE
Adjust Graph

### ISSUE THREAD

**Issue by AlinaWang2015** [michaeltandy/contraction-hierarchies#3]
Hi Michael ,

Thanks for your contribution. 
I'm trying to implement this stuff after reading your blob. Could you tell me the basic theory about adjust graph . I'm very confuse about that.

Thanks,
Alina

**Comment by michaeltandy** [comment]
It happens in https://github.com/michaeltandy/contraction-hierarchies/blob/master/src/main/java/uk/me/mjt/ch/AdjustGraphForRestrictions.java

If you're implementing the algorithm for a school project or something you can probably do without that step - it's mostly needed so turn restrictions and access-only roads are handled correctly. If you're not planning to really drive the routes, you can probably do without that.

**Comment by AlinaWang2015** [comment]
Thanks for your advice
