### ISSUE TITLE
Issue in initialization of contraction depth field value.

### ISSUE THREAD

**Issue by utkarshg42** [michaeltandy/contraction-hierarchies#4]
Hi Michael,
Thanks for sharing this code. Its pretty useful. 

Just a quick doubt on 
https://github.com/michaeltandy/contraction-hierarchies/blob/5d0fe75094ad4c767db7d17e46de1e424fa3cbcf/src/main/java/uk/me/mjt/ch/GraphContractor.java#L254
Shouldn't  it be 
`contractionDepth = Math.max(getMaxContractionDepth(n.edgesFrom), getMaxContractionDepth(n.edgesTo))) + 1`      ?

**Comment by michaeltandy** [comment]
That variable is only ever compared to other variables calculated precisely the same way (i.e. to other `ContractionOrdering` instances) so adding 1 to both would make no difference.

If we decide to perform a given contraction, the resulting `DirectedEdge` is calculated like you say:

https://github.com/michaeltandy/contraction-hierarchies/blob/5d0fe75094ad4c767db7d17e46de1e424fa3cbcf/src/main/java/uk/me/mjt/ch/DirectedEdge.java#L57
